before_script:
  - source /etc/profile
  - git submodule update --init --recursive

stages:
  - doc
  - test

doc:
  stage: doc
  script:
    - pyenv local 3.5.1
    - make doc
    - rsync -av --delete doc/_build/html/ doc-sync@docs.adfinis-sygroup.ch:/var/www/html/roche/pyaptly/

test26:
  stage: test
  script:
    - pyenv local 2.6.9
    - make webserver
    - make pytest-no-cov

test27:
  stage: test
  script:
    - pyenv local 2.7.11
    - make local-test

test3:
  stage: test
  script:
    - pyenv local 3.5.1
    - make local-test
