before_script:
  - source /etc/profile
  - git submodule update --init --recursive

stages:
  - test

test26:
  stage: test
  script:
    - pyenv local 2.6.9
    - make local-test

test27:
  stage: test
  script:
    - pyenv local 2.7.11
    - make local-test

test3:
  stage: test
  script:
    - pyenv local 3.5.1
    - make local-test
